DROP VIEW IF EXISTS top_savings_opportunities;
DROP VIEW IF EXISTS recommendation_summary_by_account;
DROP TABLE IF EXISTS rule_execution_logs;
DROP TABLE IF EXISTS recommendation_history;
DROP INDEX IF EXISTS idx_recommendations_status_savings;
DROP INDEX IF EXISTS idx_recommendations_type_severity;
DROP INDEX IF EXISTS idx_recommendations_rule_id;
ALTER TABLE recommendations DROP COLUMN IF EXISTS expires_at;
ALTER TABLE recommendations DROP COLUMN IF EXISTS resource_arn;
ALTER TABLE recommendations DROP COLUMN IF EXISTS resource_metadata;
ALTER TABLE recommendations DROP COLUMN IF EXISTS terraform_code;
ALTER TABLE recommendations DROP COLUMN IF EXISTS confidence;
ALTER TABLE recommendations DROP COLUMN IF EXISTS rule_id;
